sonata_admin:
    title: 'Sonata Admin'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }

    assets:
        extra_stylesheets:
            - 'assets/css/admin.css'

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]

        sonata.admin.block.search_result:
            contexts: [admin]

